### ISSUE TITLE
doesn't work on mobile browsers anymore

### ISSUE THREAD

**Issue by open-contracts** [Xpra-org/xpra-html5#171]
Since I updated to recent versions of the html5 client, the xpra window stays blue on mobile. I can replicate this on desktop chrome, using the mobile layout option. Looking at the chrome developer console, I get this error:

![image](https://user-images.githubusercontent.com/90533597/165654380-acfdd84e-6d11-493f-a37b-d406f93b6794.png)

Everything works just fine on desktop otherwise, and the error above does not appear either.

**Comment by totaam** [comment]
Caused by #20 / #122

We've had problems with mobile before: abfccbd68908f0f7f503174bc78c79e8c1fdcc18

**Comment by open-contracts** [comment]
thank you! setting that flag to be always true fixed it for me again. Do you think it would be a problem on lower end phones?

**Comment by totaam** [comment]
@open-contracts the commit above should fix the error you reported: we don't try to use the offscreen API when `DECODE_WORKER = false`.
But it seems like you are saying that decode worker does work on mobile?

Which specific version / mobile are you using?
Perhaps we need a better check than just `isMobile()`. @basilgello which devices / browsers were causing problems for you?

**Comment by basilgello** [comment]
@totaam it was Bromite (https://github.com/bromite/bromite) on LineageOS. No picture displayed and no packets flowing thru communication websocket. What's interesting, Chrome and Firefox do display the picture, yet without offscreen API.

I must reevaluate bromite bugs anyway, because all the bugs we had with html5 client in 2021 are still present on newer Bromites and otherwise it is the best browser on Android for me.

**Comment by totaam** [comment]
@basilgello understood, but if Bromite is the only browser hitting this issue, we should not be penalising every mobile browser.

**Comment by basilgello** [comment]
@totaam I need to do testing just like I did for audio codecs :) Let me build master trunk on Debian and make some tests tomorrow. You know I was a bit limited in my capabilities but now I settled everything a bit!

**Comment by basilgello** [comment]
@totaam I tested the latest trunk of Xpra + Xpra-HTML5 on the following Android browsers:

* Google Chrome 101.0.4951.41
* Chromium 100.0.4896.135 (built by Bromite author)
* Firefox 100.1.1
* Firefox Focus 8.16.0

and they all work with `DECODE_WORKER = true`.

Bromite, on the other side, now fails even to connect to websocket :(
I guess I will build debug Bromite and try debugging it myself.

Can you please make `DECODE_WORKER` configurable via default-settings and let it on by default so older browser users can turn it off if shit happens?

**Comment by totaam** [comment]
> Can you please make DECODE_WORKER configurable via default-settings and let it on by default so older browser users can turn it off if shit happens?

OK. I'll see if I can find the time.

**Comment by basilgello** [comment]
> OK. I'll see if I can find the time.

If I dont make it first. Maybe leave it to me then, I will do Bromite debugging anyway

**Comment by basilgello** [comment]
And Bromite 101.0.4951.53 works now too, except no floating menu bar is rendered. Menu items are rendered as text. Will investigate!

**Comment by totaam** [comment]
So, for months I ended up penalizing all mobile users for a bug that just was not in xpra at all!

**Comment by totaam** [comment]
> No, I did the tests on Chromiums too.

So there are versions of Chromium that have this problem.
But we don't know what the problem is so we can't test for it..

**Comment by basilgello** [comment]
First problem I see manifests on Python 3.9 but 3.10 is fine. Second one targeted Chromiums from 80 to 100 (roughly). Yeah we need some tests on older series.

**Comment by totaam** [comment]
> First problem I see manifests on Python 3.9 but 3.10 is fine.

There are no incompatibilities with either of these versions.
Are you sure this isn't caused by an incomplete build / wrong binary version? Something like #3536, #3531

> Second one targeted Chromiums from 80 to 100 (roughly).

If we had a Javascript console backtrace, we could add a sanity check before enabling the decoder worker.

**Comment by basilgello** [comment]
> Yeah we need some tests on older series.

I can arrange it but it needs either time or access to device testing farm :)
